attribute = "lteal"
keyword = "purple"
"keyword.directive" = { fg = "lred" } # -- preprocessor comments (#if in C)
namespace = "orange"
punctuation = "red"
"punctuation.delimiter" = "dred"
operator = "lred"
special = "lyellow"
variable = "lblue"
"variable.other.member" = "dblue"
"variable.parameter" = { fg = "purple" }
"variable.builtin" = "dpurple"
type = "lblue"
"type.builtin" = "lblue" 
constructor = { fg = "orange", modifiers = ["bold"]}
function = { fg = "yellow", modifiers = ["italic"]}
"function.macro" = { fg = "dyellow"}
"function.builtin" = { fg = "dred"}
tag = "cyan"
comment = { fg = "gray", modifiers = ["italic"]}
constant = "lpurple"
"constant.builtin" = { fg = "purple", modifiers = ["italic"]}
string = "green"
"constant.numeric" = "purple"
"constant.character.escape" = "orange"
# used for lifetimes
label = "purple"

"markup.heading" = "lred"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "lblue" ,modifiers = ["underlined"] }
"markup.link.text" = "fg_gray"
"markup.raw" = "fg"

"diff.plus" = { fg =  "vadd"}
"diff.minus" = { fg = "vdelete" }
"diff.delta" = { fg = "vchange" }

"ui.background" = { bg = "bg" }
"ui.linenr" = { fg = "fg_gutter_light"}
"ui.linenr.selected" = { fg = "lorange", modifiers = ["bold"]  }
"ui.statusline" = { fg = "barfg", bg = "barbg" }
"ui.statusline.inactive" = { fg = "gray", bg = "bg" }
"ui.popup" = { fg = "gray" , bg = "fg_gutter" }
"ui.window" = { fg = "bg_hi", bg = "gray", modifiers = [ ] }
"ui.help" = { bg = "fg_gutter", fg = "fg_gray", modifiers = [ ] }

"ui.text" = { fg = "ui.fg", modifiers = [] }
"ui.text.focus" = { fg = "white", modifiers = ["bold"] }

"ui.selection" = { bg = "bg_sel", modifiers = ["reversed"] }
"ui.selection.primary" = { bg = "bg_ser" }
"ui.cursor.select" = { bg = "delta" }
"ui.cursor.insert" = { bg = "white" }
"ui.cursor.match" = { fg = "bg", bg = "#yellow" }
"ui.cursor" = { modifiers = ["reversed"] }
"ui.highlight" = { bg = "bg" }

"ui.menu.selected" = { fg = "revolver", bg = "white" }

diagnostic = { modifiers = ["underlined"] }

warning = "lightning"
error = "apricot"
info = "delta"
hint = "silver"

[palette]
lblue    = "#aacfff"
blue    = "#9abff0"
dblue    = "#7fa0ea"
ddblue    = "#6a90df"

lcyan    = "#8feaef"
cyan    = "#7fd0da"
dcyan    = "#5fc0cf"

lteal    = "#9aeaaf"
teal    = "#7fd0aa"
dteal    = "#60c09f"

green   = "#d5ff80"
dgreen   = "#c0fa70"
ddgreen   = "#aff060"

llyellow  = "#ffeaaf"
lyellow  = "#ffda8f"
yellow  = "#ffca6f"
dyellow  = "#f0ba5f"
ddyellow  = "#eaaa5a"

orange  = "#ffaf6f"
dorange  = "#f09a5f"
ddorange  = "#ea8f5a"

lred     = "#ff9a9f"
red     = "#fa8a8f"
dred     = "#f07a6f"

lmagenta = "#fa9aca"
magenta = "#fa9aca"
dmagenta = "#f080ba"
ddmagenta = "#ea70aa"

lurple  = "#cfafff"
purple  = "#b0a0fa"
durple  = "#aa90ef"
ddurple  = "#a09aea"

white   = "#faf7ea"
white2   = "#d9d7ce"

# Git
vadd    = "#cce78e"
vchange = "#95e6bb"
vdelete = "#ff90a0"

# UI

## EDITOR
bgd    = "#151a22"
bg     = "#171c26"
fg     = "#d9d7ce"
bg_hi  = "#242b39"
bg_dhi = "#141a24"
bg_sel = "#302e50"
bg_ser = "#404e6a"

barbg = "#202630"
barfg     = "#4d525a"

gray           = "#556575"
fg_gray        = "#c3c0ba"

bg_foc   = "#526370"
bg_fochi = "#677380"
bg_sfochi= "#607080"

fg_gutter      = "#343f4c"
fg_gutter_light= "#4d4751"

## UI PANEL





